# Generated by Django 3.1.6 on 2021-02-10 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('tipo_documento', models.CharField(choices=[('ti', 'Tarjeta de identidad'), ('cc', 'Cedula de ciudadania')], max_length=50)),
                ('numero_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('ocupacion', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlUsuarios.plan')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlUsuarios.sucursal')),
            ],
        ),
    ]
